"""Regression guard: Python and C hash mixers must produce identical values.

Any drift between python/blueprint_v2.py's _bp_mix64 / _hash_combine and
src/mccfr_blueprint.c's versions causes silent lookup failures in every
consumer that recomputes info-set hashes from action histories. This test
holds the expected values constant — update them (AND update the C side's
tests/test_hash_sync.c generator output) if the mixer is intentionally
changed.

Vectors generated by tests/test_hash_sync.c. To regenerate after an
intentional mixer change:

    gcc -O2 tests/test_hash_sync.c -o build/test_hash_sync
    ./build/test_hash_sync

Then copy the outputs into EXPECTED_MIX / EXPECTED_HC / EXPECTED_AH below.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_HERE)
sys.path.insert(0, os.path.join(_REPO, "python"))

from blueprint_v2 import _bp_mix64, _hash_combine, _compute_action_hash


EXPECTED_MIX = [
    (0x0000000000000000, 0x0000000000000000),
    (0x0000000000000001, 0x5692161d100b05e5),
    (0x0000000000000002, 0xdbd238973a2b148a),
    (0x000000000000002a, 0xa759ea27d4727622),
    (0x00000000deadbeef, 0x4e062702ec929eea),
    (0x123456789abcdef0, 0x9629f58e8ec5b906),
    (0xfedcba9876543210, 0xee128d82ce22fe61),
    (0xffffffffffffffff, 0xb4d055fcf2cbbd7b),
]

EXPECTED_HC = [
    ((0x0000000000000000, 0x0000000000000000), 0x0000000000000000),
    ((0x0000000000000001, 0x0000000000000002), 0x3ec2d42f3a45cc6e),
    ((0x123456789abcdef0, 0xfedcba9876543210), 0x5666e87d28fd0f04),
    ((0x00000000deadbeef, 0x00000000cafebabe), 0x06abd408646bde6f),
]

EXPECTED_AH = [
    ([], 0xfedcba9876543210),
    ([0], 0x60b50dc9f2150eba),
    ([1], 0x03b866c6bd177d00),
    ([0, 1, 2], 0x0467d7d92c2b089e),
    ([2, 1, 0, 3, 2, 1], 0x967d2138a6a1010c),
]


def main() -> int:
    failures = 0

    print("=== _bp_mix64 ===")
    for x, expected in EXPECTED_MIX:
        got = _bp_mix64(x)
        if got != expected:
            print(f"  FAIL _bp_mix64({x:#018x}): got {got:#018x}, expected {expected:#018x}")
            failures += 1
        else:
            print(f"  OK   _bp_mix64({x:#018x}) = {got:#018x}")

    print("\n=== _hash_combine ===")
    for (a, b), expected in EXPECTED_HC:
        got = _hash_combine(a, b)
        if got != expected:
            print(f"  FAIL _hash_combine({a:#018x}, {b:#018x}): got {got:#018x}, expected {expected:#018x}")
            failures += 1
        else:
            print(f"  OK   _hash_combine({a:#018x}, {b:#018x}) = {got:#018x}")

    print("\n=== _compute_action_hash ===")
    for actions, expected in EXPECTED_AH:
        got = _compute_action_hash(actions)
        if got != expected:
            print(f"  FAIL _compute_action_hash({actions}): got {got:#018x}, expected {expected:#018x}")
            failures += 1
        else:
            print(f"  OK   _compute_action_hash({actions}) = {got:#018x}")

    if failures:
        print(f"\n{failures} hash mismatches — Python and C are OUT OF SYNC")
        print("If this is intentional, regenerate vectors from tests/test_hash_sync.c")
        return 1
    print("\nAll hash vectors match C reference.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
